import { useCallback, useEffect, useState } from 'react'
import { ArrowUpRight, RefreshCw, Sunrise } from 'lucide-react'
import { LoadingState } from '../../components/ui/states'
import Button from '../../components/ui/Button'
import ZoneHeader from '../../components/ZoneHeader'
import { CONTAINERS } from '../../lib/design-tokens'

/**
 * Daily Brief zone — renders the weekly synthesis generated by the Obsidian
 * vault routine (OB CLAUDE vault → 🌅 Daily Brief). The vault's
 * `dashboard-ui/build.py` snapshots the latest brief into
 * `public/data/daily-brief.json`; this zone only *consumes* that snapshot —
 * it never re-derives anything.
 */

type BriefTool = { name: string; desc: string }
type BriefHandoff = { name: string; note: string }
type BriefTrack = { title: string; bpm: string; key: string; scale: string }
type BriefResurface = { name: string; note: string }

interface BriefJson {
  date: string
  active_project: string
  synthesis: string[]
  tools: BriefTool[]
  tracks: BriefTrack[]
  handoffs: BriefHandoff[]
  resurface: BriefResurface[]
}

const DATA_URL = '/data/daily-brief.json'

function formatDate(iso: string): string {
  const d = new Date(`${iso}T00:00:00`)
  if (Number.isNaN(d.getTime())) return iso || '—'
  return d.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })
}

function initials(name: string): string {
  const parts = name.split(/[\s\-—]+/).filter(Boolean)
  if (parts.length === 0) return '•'
  if (parts.length === 1) return parts[0].slice(0, 2).toUpperCase()
  return (parts[0][0] + parts[1][0]).toUpperCase()
}

function SectionCard({
  title,
  count,
  children,
}: {
  title: string
  count?: number
  children: React.ReactNode
}) {
  return (
    <section
      className="rounded-2xl border p-5 sm:p-6"
      style={{ background: 'var(--bg-card)', borderColor: 'var(--border-soft)' }}
    >
      <div className="mb-4 flex items-center gap-2">
        <h2
          className="text-xs font-semibold uppercase tracking-wider"
          style={{ color: 'var(--text-3)' }}
        >
          {title}
        </h2>
        {count != null ? (
          <span className="ml-auto rounded-full bg-emerald-500/10 px-2.5 py-0.5 text-xs font-semibold text-emerald-600">
            {count}
          </span>
        ) : null}
      </div>
      {children}
    </section>
  )
}

export default function DailyBriefZone() {
  const [data, setData] = useState<BriefJson | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)

  const load = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      const res = await fetch(`${DATA_URL}?t=${Date.now()}`, { cache: 'no-store' })
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      setData((await res.json()) as BriefJson)
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to load brief')
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect -- fetch the brief JSON on mount; the loading flag before the await is intentional
    void load()
  }, [load])

  return (
    <div className="flex-1 overflow-auto" style={{ background: 'var(--bg-canvas)', color: 'var(--text-1)' }}>
      <div className={`${CONTAINERS.narrow} py-8 space-y-5`}>
        <ZoneHeader
          title="Daily Brief"
          icon={Sunrise}
          description={
            data ? (
              <>
                {formatDate(data.date)} · focus{' '}
                <span className="inline-flex items-center rounded-full bg-emerald-500/10 px-2.5 py-0.5 text-xs font-semibold text-emerald-600">
                  {data.active_project}
                </span>
              </>
            ) : (
              'Synthesized weekly from the Obsidian vault — tools, handoffs, and tracks for the active project.'
            )
          }
          actions={
            <Button
              variant="secondary"
              onClick={() => void load()}
              disabled={loading}
              leading={<RefreshCw className={`size-4 ${loading ? 'animate-spin' : ''}`} aria-hidden />}
            >
              Refresh
            </Button>
          }
        />

        {loading && !data ? <LoadingState label="Loading brief…" /> : null}

        {error && !data ? (
          <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">
            <p className="font-medium">No brief snapshot found</p>
            <p className="mt-1 text-amber-800/90">
              Run <code className="rounded bg-amber-100/80 px-1">python3 build.py</code> in the vault&apos;s{' '}
              <code className="rounded bg-amber-100/80 px-1">dashboard-ui/</code> folder to sync{' '}
              <code className="rounded bg-amber-100/80 px-1">public/data/daily-brief.json</code>, then redeploy. ({error})
            </p>
          </div>
        ) : null}

        {data ? (
          <>
            {/* Synthesis */}
            <section
              className="rounded-2xl border p-6 sm:p-7"
              style={{ background: 'var(--bg-card)', borderColor: 'var(--border-soft)' }}
            >
              <h2
                className="mb-3 text-xs font-semibold uppercase tracking-wider"
                style={{ color: 'var(--text-3)' }}
              >
                Today’s synthesis
              </h2>
              <div className="space-y-3 text-[17px] leading-relaxed" style={{ color: 'var(--text-1)' }}>
                {data.synthesis.length > 0 ? (
                  data.synthesis.map((p, i) => <p key={i}>{p}</p>)
                ) : (
                  <p className="text-sm italic" style={{ color: 'var(--text-3)' }}>
                    No synthesis yet — run the brief routine.
                  </p>
                )}
              </div>
            </section>

            {/* Tools + Handoffs */}
            <div className="grid gap-5 md:grid-cols-2">
              <SectionCard title="Today’s tools" count={data.tools.length}>
                <ul className="space-y-1">
                  {data.tools.length > 0 ? (
                    data.tools.map(t => (
                      <li
                        key={t.name}
                        className="flex items-start gap-3 rounded-xl p-2.5 transition-colors hover:[background:var(--bg-muted)]"
                      >
                        <span className="grid size-9 shrink-0 place-items-center rounded-lg bg-emerald-500/10 text-xs font-semibold text-emerald-600">
                          {initials(t.name)}
                        </span>
                        <span className="min-w-0">
                          <span className="block text-sm font-semibold" style={{ color: 'var(--text-1)' }}>
                            {t.name}
                          </span>
                          <span className="block text-xs leading-relaxed" style={{ color: 'var(--text-3)' }}>
                            {t.desc}
                          </span>
                        </span>
                      </li>
                    ))
                  ) : (
                    <li className="text-sm italic" style={{ color: 'var(--text-3)' }}>
                      No tools surfaced.
                    </li>
                  )}
                </ul>
              </SectionCard>

              <SectionCard title="Pending handoffs" count={data.handoffs.length}>
                <ul className="space-y-1">
                  {data.handoffs.length > 0 ? (
                    data.handoffs.map(h => (
                      <li
                        key={h.name}
                        className="flex items-start gap-3 rounded-xl p-2.5 transition-colors hover:[background:var(--bg-muted)]"
                      >
                        <span className="mt-0.5 shrink-0 rounded-full bg-emerald-500/10 px-2.5 py-0.5 text-[11px] font-semibold text-emerald-600">
                          open
                        </span>
                        <span className="min-w-0">
                          <span className="block text-sm font-semibold" style={{ color: 'var(--text-1)' }}>
                            {h.name}
                          </span>
                          <span className="block text-xs leading-relaxed" style={{ color: 'var(--text-3)' }}>
                            {h.note}
                          </span>
                        </span>
                      </li>
                    ))
                  ) : (
                    <li className="text-sm italic" style={{ color: 'var(--text-3)' }}>
                      No open handoffs.
                    </li>
                  )}
                </ul>
              </SectionCard>
            </div>

            {/* Tracks */}
            <SectionCard title="Recent tracks" count={data.tracks.length}>
              <ul className="space-y-2">
                {data.tracks.length > 0 ? (
                  data.tracks.map(t => (
                    <li
                      key={t.title}
                      className="flex flex-wrap items-center justify-between gap-3 rounded-xl border px-4 py-3"
                      style={{ borderColor: 'var(--border-soft)', background: 'var(--bg-card-soft)' }}
                    >
                      <span className="text-sm font-semibold" style={{ color: 'var(--text-1)' }}>
                        {t.title}
                      </span>
                      <span className="flex flex-wrap gap-2">
                        <span className="rounded-full bg-emerald-500/10 px-2.5 py-0.5 text-xs font-semibold tabular-nums text-emerald-600">
                          {t.bpm} BPM
                        </span>
                        <span
                          className="rounded-full border px-2.5 py-0.5 text-xs tabular-nums"
                          style={{ borderColor: 'var(--border-soft)', color: 'var(--text-2)' }}
                        >
                          {t.key}
                        </span>
                        <span
                          className="rounded-full border px-2.5 py-0.5 text-xs"
                          style={{ borderColor: 'var(--border-soft)', color: 'var(--text-2)' }}
                        >
                          {t.scale}
                        </span>
                      </span>
                    </li>
                  ))
                ) : (
                  <li className="text-sm italic" style={{ color: 'var(--text-3)' }}>
                    No tracks synced yet — wire the YouTube playlist into media-sync.
                  </li>
                )}
              </ul>
            </SectionCard>

            {/* Resurface */}
            {data.resurface.length > 0 ? (
              <SectionCard title="Worth resurfacing">
                <ul className="space-y-1">
                  {data.resurface.map(r => (
                    <li key={r.name} className="flex items-start gap-3 rounded-xl p-2.5">
                      <ArrowUpRight className="mt-0.5 size-4 shrink-0 text-emerald-600" aria-hidden />
                      <span className="min-w-0">
                        <span className="block text-sm font-semibold" style={{ color: 'var(--text-1)' }}>
                          {r.name}
                        </span>
                        <span className="block text-xs leading-relaxed" style={{ color: 'var(--text-3)' }}>
                          {r.note}
                        </span>
                      </span>
                    </li>
                  ))}
                </ul>
              </SectionCard>
            ) : null}

            <p className="px-1 text-xs" style={{ color: 'var(--text-4)' }}>
              Generated by the vault’s weekly synthesis routine · snapshot synced via{' '}
              <code className="rounded px-1" style={{ background: 'var(--bg-muted)' }}>
                dashboard-ui/build.py
              </code>{' '}
              · signal up, rules down
            </p>
          </>
        ) : null}
      </div>
    </div>
  )
}
